ModelArguments:
  base_model_name: t5-small
  hidden_dropout_prob: 0.0
  num_beams: 4
  max_length: 128
  top_k: 50
  top_p: 0.95
  temperature: 1.0
  length_penalty: 2.0
  repetition_penalty: 1.0
  early_stopping: True
  no_repeat_ngram_size: 3
  do_sample: True

# TrainingArguments are overwritten by not-None arguments
TrainingArguments:
  project_name: T5_YTASL
  model_name: T5_YTASL_pretrain
  output_dir: ./results
  seed: 42
  resume_from_checkpoint: none
  load_only_weights: False
#  Logging and saving
  report_to: wandb
  logging_steps: 1
  eval_steps: 200
  save_steps: 100
  push_to_hub: False
#  Debugging
  max_train_samples: none
  max_val_samples: none
#  Training
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 4
  learning_rate: 0.001
  lr_scheduler_type: constant
  max_training_steps: 20000
  weight_decay: 0.0
  fp16: False
#  Data processing
  max_sequence_length: 250
  max_token_length: 128
  skip_frames: False
#  Evaluation
  num_beams: 5
  early_stopping: False
  no_repeat_ngram_size: 0

SignDataArguments:
  data_dir: /media/zeleznyt/DATA/data/YTASL_small
  annotation_path:
    train: YT.annotations.train.json
    dev: YT.annotations.dev.json
  visual_features:
    sign2vec:
      enable_input: False
      train: sign2vec/metadata_sign2vec.train.json
      dev: sign2vec/metadata_sign2vec.dev.json
    mae:
      enable_input: False
      train: mae/metadata_mae.train.json
      dev: mae/metadata_mae.dev.json
    dino:
      enable_input: False
      train: dino/metadata_dino.train.json
      dev: dino/metadata_dino.dev.json
    pose:
      enable_input: True
      train: YouTubeASL.keypoints.train.json
      dev: YouTubeASL.keypoints.dev.json

SignModelArguments:
  projectors:
    sign2vec:
      dim: 768
    mae:
      dim: 768
    dino:
      dim: 1152
    pose:
      dim: 208